apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup
  namespace: velero
spec:
  schedule: 0 3 * * *
  template:
    includedNamespaces:
    - '*'
    excludedNamespaces:                
      - cert-manager                                       
      - default                                                 
      - ingress-nginx                 
      - kube-public                   
      - kube-system                   
      - velero  
    includedResources:
    - '*'
    storageLocation: default
    volumeSnapshotLocations:
      - default
    ttl: 720h
